
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_zero(object):
    def setupUi(self, zero):
        zero.setObjectName("zero")
        zero.resize(309, 226)
        self.centralwidget = QtWidgets.QWidget(zero)
        self.centralwidget.setObjectName("centralwidget")
        self.inputLabel = QtWidgets.QLabel(self.centralwidget)
        self.inputLabel.setEnabled(True)
        self.inputLabel.setGeometry(QtCore.QRect(10, 0, 291, 41))
        self.inputLabel.setAutoFillBackground(True)
        self.inputLabel.setText("")
        self.inputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputLabel.setObjectName("inputLabel")
        self.three = QtWidgets.QPushButton(self.centralwidget)
        self.three.setGeometry(QtCore.QRect(160, 60, 75, 23))
        self.three.setObjectName("three")
        self.two = QtWidgets.QPushButton(self.centralwidget)
        self.two.setGeometry(QtCore.QRect(80, 60, 75, 23))
        self.two.setObjectName("two")
        self.four = QtWidgets.QPushButton(self.centralwidget)
        self.four.setGeometry(QtCore.QRect(0, 90, 75, 23))
        self.four.setObjectName("four")
        self.one = QtWidgets.QPushButton(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(0, 60, 75, 23))
        self.one.setObjectName("one")
        self.six = QtWidgets.QPushButton(self.centralwidget)
        self.six.setGeometry(QtCore.QRect(160, 90, 75, 23))
        self.six.setObjectName("six")
        self.seven = QtWidgets.QPushButton(self.centralwidget)
        self.seven.setGeometry(QtCore.QRect(0, 120, 75, 23))
        self.seven.setObjectName("seven")
        self.five = QtWidgets.QPushButton(self.centralwidget)
        self.five.setGeometry(QtCore.QRect(80, 90, 75, 23))
        self.five.setObjectName("five")
        self.eight = QtWidgets.QPushButton(self.centralwidget)
        self.eight.setGeometry(QtCore.QRect(80, 120, 75, 23))
        self.eight.setObjectName("eight")
        self.nine = QtWidgets.QPushButton(self.centralwidget)
        self.nine.setGeometry(QtCore.QRect(160, 120, 75, 23))
        self.nine.setObjectName("nine")
        self.zero = QtWidgets.QPushButton(self.centralwidget)
        self.zero.setGeometry(QtCore.QRect(0, 150, 75, 31))
        self.zero.setObjectName("zero")
        self.sum = QtWidgets.QPushButton(self.centralwidget)
        self.sum.setGeometry(QtCore.QRect(240, 60, 51, 31))
        self.sum.setObjectName("sum")
        self.subtract = QtWidgets.QPushButton(self.centralwidget)
        self.subtract.setGeometry(QtCore.QRect(240, 90, 51, 31))
        self.subtract.setObjectName("subtract")
        self.divide = QtWidgets.QPushButton(self.centralwidget)
        self.divide.setGeometry(QtCore.QRect(240, 120, 51, 31))
        self.divide.setObjectName("divide")
        self.enter = QtWidgets.QPushButton(self.centralwidget)
        self.enter.setGeometry(QtCore.QRect(80, 150, 75, 31))
        self.enter.setObjectName("enter")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(160, 150, 75, 31))
        self.clear.setObjectName("clear")
        self.multiply = QtWidgets.QPushButton(self.centralwidget)
        self.multiply.setGeometry(QtCore.QRect(240, 150, 51, 31))
        self.multiply.setObjectName("multiply")
        zero.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(zero)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 309, 21))
        self.menubar.setObjectName("menubar")
        zero.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(zero)
        self.statusbar.setObjectName("statusbar")
        zero.setStatusBar(self.statusbar)

        self.retranslateUi(zero)
        QtCore.QMetaObject.connectSlotsByName(zero)

    def retranslateUi(self, zero):
        _translate = QtCore.QCoreApplication.translate
        zero.setWindowTitle(_translate("zero", "Calculator"))
        self.three.setText(_translate("zero", "3"))
        self.two.setText(_translate("zero", "2"))
        self.four.setText(_translate("zero", "4"))
        self.one.setText(_translate("zero", "1"))
        self.six.setText(_translate("zero", "6"))
        self.seven.setText(_translate("zero", "7"))
        self.five.setText(_translate("zero", "5"))
        self.eight.setText(_translate("zero", "8"))
        self.nine.setText(_translate("zero", "9"))
        self.zero.setText(_translate("zero", "0"))
        self.sum.setText(_translate("zero", "+"))
        self.subtract.setText(_translate("zero", "-"))
        self.divide.setText(_translate("zero", "/"))
        self.enter.setText(_translate("zero", "ENTER"))
        self.clear.setText(_translate("zero", "C"))
        self.multiply.setText(_translate("zero", "*"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    zero = QtWidgets.QMainWindow()
    ui = Ui_zero()
    ui.setupUi(zero)
    zero.show()
    sys.exit(app.exec_())


